hack/verify/verify_boilerplate.py
It seems like this script isn't using any python3-specific features, and the default golang image doesn't have python3 (which makes running this in CI more annoying).
=> verify_boilerplate: don't require python3

aws-janitor/resources/elb.go, aws-janitor/resources/elbv2.go, aws-janitor/resources/list.go
I imported this change from test-infra (https://github.com/kubernetes/test-infra/pull/17565).
I basically copied the existing elb code but updated it to use the elbv2 API.
I've tested this with `aws-resources-list` (since the janitor doesn't have a `--dry-run` mode) and it shows the elbv2 resources appropriately. (I don't have any elb [v1] resources in my account but it's probably still working...)
There's lots of boilerplate here. At some point we should probably clean up some of this code to make it more maintainable...
/assign @detiber 
cc @chemikadze
=> aws-janitor: clean up elbv2 resources

Makefile, images/cloudbuild.yaml
Rather than using `gcr.io/k8s-prow`, we should probably use our own staging project.
I've created https://github.com/kubernetes/k8s.io/pull/890 to initiate this process. We shouldn't merge this PR until it's in, probably.
/hold
=> Switch to gcr.io/k8s-staging-boskos

deployments/base/cleaner/deployment.yaml, deployments/base/cleaner/kustomization.yaml, deployments/base/cleaner/rbac.yaml, deployments/base/crd.yaml, deployments/base/deployment.yaml, deployments/base/janitor/README.md, deployments/base/janitor/deployment.yaml, deployments/base/janitor/kustomization.yaml, deployments/base/janitor/serviceaccount.yaml, deployments/base/kustomization.yaml, deployments/base/rbac.yaml, deployments/base/reaper/README.md, deployments/base/reaper/deployment.yaml, deployments/base/reaper/kustomization.yaml, deployments/base/service.yaml, deployments/overlays/example/README.md, deployments/overlays/example/boskos-resources.yaml, deployments/overlays/example/kustomization.yaml, deployments/overlays/example/namespace.yaml, deployments/overlays/example/numeric-janitor/kustomization.yaml, deployments/overlays/example/phonetic-janitor/kustomization.yaml
I know we haven't really discussed exactly how we want deployments to work long-term, and I'm not sure how this integrates with bazel-based deployment systems (such as kubernetes/test-infra), but I think that using kustomize generally makes things pretty clear to understand. I guess you can always run `kustomize` and save the output into static YAML files.
I took the existing manifests from kubernetes/test-infra, plus a few others, and massaged them a bit to simplify them.
I haven't yet added the AWS janitor into the mix, though that should be a fairly straightforward followup.
I also didn't enable v2 of the cleaner, since that isn't widely deployed, and it'll probably be helpful to see the diff, anyway.
I've tested this on a kind cluster with `kustomize build deployments/overlays/example …
=> Create an opinionated Boskos deployment using kustomize

cmd/janitor/gcp_janitor.py
This was last updated a few months ago, and there are more zones now.
I think this is probably safer than relying on `gcloud` to do the right thing itself, given outages we've had in the past. Long-term we still plan to rewrite this janitor in Go.
=> gcp-janitor: update list of GCP zones

cmd/janitor/gcp_janitor.py, images/janitor/Dockerfile
I hadn't tested #34 enough; after it was merged, I realized the version of `gcloud` in the janitor image was too old.
I updated that, which then revealed two new problems:
- python2 was no longer part of the image
- the GKE hub API isn't enabled on projects by default
I updated the script to be python3-compatible (I believe), and I added guards to ensure the necessary GCP APIs are enabled on the project. (If they aren't, we just skip those resources.)
=> GCP janitor: support GKE hub memberships safely

cmd/janitor/gcp_janitor.py
This change adds an additional attribute to Resources in the GCP janitor, allowing specifying a list of names that should never be deleted.
This functionality is used to ensure that the `_Default` and `_Required` logging sinks are never deleted.
(More hacks, my favorite!)
Fixes #37
=> GCP janitor: don't attempt to delete undeletable logging sinks

Makefile
If k/k is using go1.15, then it's good enough for us!
=> Update to go1.15.1

.gitignore, cleaner/cleaner_test.go, handlers/handlers.go, mason/mason_test.go, ranch/priority.go, ranch/ranch.go, ranch/ranch_test.go
The labels of existing histogram `httpRequestDuration` is not enough for `/acquire` endpoints.
We define a new one here.
This will help us to understand the impact of lease pool size changes.
/cc @stevekuznetsov @alvaroaleman
=> Expose metric boskos_acquire_duration_seconds

Makefile, images/boskosctl/Dockerfile
The boskosctl image has been failing to build, since apparently the version of alpine we were using was no longer supported:
```
Step 3/18 : FROM golang:${go_version}-alpine${alpine_version} as build
manifest for golang:1.15.1-alpine3.11 not found: manifest unknown: manifest unknown
make: *** [Makefile:65: boskosctl-image] Error 1
```
=> Update to go 1.15.2 and alpine 3.12

aws-janitor/resources/addresses.go, aws-janitor/resources/asg.go, aws-janitor/resources/clean.go, aws-janitor/resources/cloud_formation_stacks.go, aws-janitor/resources/dhcp_options.go, aws-janitor/resources/elb.go, aws-janitor/resources/elbv2.go, aws-janitor/resources/iam_instance_profiles.go, aws-janitor/resources/iam_roles.go, aws-janitor/resources/instance.go, aws-janitor/resources/internet_gateways.go, aws-janitor/resources/launch_configs.go, aws-janitor/resources/launch_templates.go, aws-janitor/resources/list.go, aws-janitor/resources/nat_gateway.go, aws-janitor/resources/network_interface.go, aws-janitor/resources/route53.go, aws-janitor/resources/route_tables.go, aws-janitor/resources/security_groups.go, aws-janitor/resources/set.go, aws-janitor/resources/subnets.go, aws-janitor/resources/volumes.go, aws-janitor/resources/vpcs.go, cmd/aws-janitor-boskos/main.go, cmd/aws-janitor/main.go, cmd/aws-resources-list/main.go
We'd like to use the AWS janitor in some additional places, but the lack of a "dry-run" functionality to validate what it'll do makes me nervous.
I started by refactoring the various resources methods to take an `Options` struct. The main reason I did this instead of just adding a dry-run boolean is that I intend to further extend this with additional configuration (such as include/exclude labels).
The dry-run functionality just builds on this new Options struct.
/assign @detiber
=> aws-janitor: add --dry-run functionality

aws-janitor/regions/regions.go, aws-janitor/resources/clean.go, cmd/aws-janitor/main.go, cmd/aws-resources-list/main.go
While testing https://github.com/kubernetes-sigs/boskos/pull/47 I couldn't figure out why certain operations were getting stuck, until I realized I wasn't using a valid region name.
This PR adds some validation to fail-fast if an invalid region is used (e.g. `us-west2` instead of `us-west-2`).
=> aws-janitor: validate region flag

aws-janitor/resources/efs.go, aws-janitor/resources/list.go
This PR adds support for cleaning up [Elastic File Systems](https://aws.amazon.com/efs/).
In order to delete file systems we must first delete all associated mount targets and wait for them to be deleted.
This `MarkAndSweep()` implementation is a little long; let me know if you'd prefer this broken into smaller functions.
@msau42
=> Mark and sweep elastic file systems

aws-janitor/resources/list.go, aws-janitor/resources/snapshots.go
This PR adds support for cleaning up [EBS volume snapshots](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSSnapshots.html).
@msau42 @ixdy
=> Mark and sweep EBS volume snapshots

cmd/janitor/gcp_janitor.py
Not sure if we can add arbitrary GCP resources for Janitor to clean up, but the use case is in some of the Knative integration test flows, they create `pubsub` resources which are possible to be leaked. Currently we are running the `gcloud pubsub delete` commands before the workflow actually starts, but the best way seems to be asking Janitor to clean them up.
I'm setting `tolerate=True` here, then it won't report as failure if the cleanup command fails(?)
=> GCP Janitor also cleans up pubsub resources

cmd/boskos/boskos.go, ranch/ranch.go, ranch/ranch_test.go, ranch/storage.go
First commit: Make config sync a controller
* We need to retry on errors
* We need to react to changes in resources, specifically Add/Delete or Update where a resource gets set into `Tombstome` state
Second commit: Fix config sync when a config is changed from static -> dynamic -> static
This currently causes an `IsAlreadyExists` error because the calculation for the static resource creation ignores all resources that have a corresponding dynamic config. This blocks any further progress.
-> Fixed by including all resources that have a static config in the static resource add/delete calculation
-> This made the dynamic resource reconciliation instantly delete them. Fixed by making the dynamic resource reconciliation ignore all resources that have a static config
Note: While I added a unit …
=> Fix configsync for static -> dynamic -> static

OWNERS_ALIASES
@richardcase and @randomvariable are  the active maintainers for https://github.com/kubernetes-sigs/cluster-api-provider-aws at present, with @detiber primarily focused on Equinix atm, so we are swapping places.
=> OWNERS_ALIASES: Swap out aws-janitor contributors

aws-janitor/resources/addresses.go, aws-janitor/resources/asg.go, aws-janitor/resources/cloud_formation_stacks.go, aws-janitor/resources/dhcp_options.go, aws-janitor/resources/efs.go, aws-janitor/resources/elb.go, aws-janitor/resources/elbv2.go, aws-janitor/resources/iam_instance_profiles.go, aws-janitor/resources/iam_roles.go, aws-janitor/resources/instance.go, aws-janitor/resources/internet_gateways.go, aws-janitor/resources/launch_configs.go, aws-janitor/resources/launch_templates.go, aws-janitor/resources/nat_gateway.go, aws-janitor/resources/network_interface.go, aws-janitor/resources/route53.go, aws-janitor/resources/route_tables.go, aws-janitor/resources/security_groups.go, aws-janitor/resources/set.go, aws-janitor/resources/set_test.go, aws-janitor/resources/snapshots.go, aws-janitor/resources/subnets.go, aws-janitor/resources/volumes.go, aws-janitor/resources/vpcs.go
Many resources don't have a readily accessible creation timestamp in their metadata, but at least some of them do, so we may as well make use of it when available.
/assign @detiber 
cc @chemikadze
=> aws-janitor: use creation timestamp when available

aws-janitor/resources/list.go, aws-janitor/resources/sqs.go
This PR adds aws-janitor to clean up SQS queues and  EventBridge rules.
=> aws-janitor: Cleanup SQS queues and EventBridge rules

cmd/aws-janitor-boskos/main.go
...to collect the response time when cleaning and for the entire process when doing the janitor process
Make the histogram and created the exponential buckets, I've spoken in the past with `Frederic Branczyk - @brancz` and he suggests following this approach since it is very similar to what I've implemented in the past then used the same 😄 
this is part of https://github.com/kubernetes-sigs/boskos/issues/13
opening this PR for feedback and see if sounds good, and then will do it for the other janitors
/assign @ixdy
=> aws-janitor-boskos: add clean time and process time metrics 

cmd/aws-janitor/main.go
...to collect the response time when running this job
this is a short live job, and then we cannot guarantee that we will have someone to scrape the data at the correct time, to avoid that, we need to use the Prometheus PushGateway to store the metrics and then have Prometheus scrape the PushGateway, however, the problem continues, we need to make sure the metrics are pushed to the PushGateway in time.
So for that, we need to push ourselves, then the approach in this PR is to push when exiting the job
this is part of https://github.com/kubernetes-sigs/boskos/issues/13
opening this PR for feedback and see if sounds good
a screenshot for the metric pushed to PushGateway
/assign @ixdy
=> aws-janitor: add job duration metric

aws-janitor/resources/iam_roles.go
/assign @richardcase @randomvariable
cc @chemikadze
It's a singular account, not plural. :(
=> aws-janitor: fix typo in OrganizationAccountAccessRole

aws-janitor/resources/route53.go
* Strip the `/hostedzone/` prefix from zone IDs returned by ListHostedZones before passing them to other route53 API requests. This is due to an inconsistency in the Route53 API.
aws-janitor jobs are [currently failing](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/1383470582967832576#1:build-log.txt%3A38) with this error: `No hosted zone found with ID: /hostedzone/ZEMLNXIIWQ0RV`.
Local testing confirms that `ListHostedZones` returns an ID of the form `/hostedzone/ABCDEF12345678` but `ListTagsForResources` expects IDs of the form `ABCDEF12345678`, otherwise it returns an error.
* Ensure kops-controller DNS records are also deleted. [Recent kops versions create these records](https://github.com/kubernetes/kops/blob/27f05ca939b758379ed9cb8a1cbbd6fa0d8db7bc/up …
=> aws-janitor: Route53 Improvements

aws-janitor/resources/route53.go
Followup to https://github.com/kubernetes-sigs/boskos/pull/80
aws-janitor jobs are [still failing with the same error](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/1384259018888843264). It seems that we need to fix the ListHostedZones output in MarkAndSweep in addition to ListAll.
=> aws-janitor: trim hostedzone ID prefix in MarkAndSweep

aws-janitor/resources/route53.go, aws-janitor/resources/route53_test.go
This updates the Route53 record pattern for kOps' etcd records - these records were only used by kOps' legacy etcd implementation (before etcd-manager). See [this](https://github.com/kubernetes/kops/blob/06ca1ff169af82f78c59ffc17cf966fdd2b74898/upup/pkg/fi/cloudup/dns.go#L250-L261) code block and know that we don't have any prow jobs that test legacy etcd anymore, it will be removed altogether soon.
The new etcd format is what kOps creates when provisioning dedicated apiservers that connect to etcd remotely. See [this](https://github.com/kubernetes/kops/blob/044a59ab97dc1407f45f13aba5d707677be8c020/nodeup/pkg/model/kube_apiserver.go#L322-L323) code block.
The [aws-janitor logs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/1384654184124518400) mention …
=> aws-janitor - Update Route53 name regexes for kOps' new etcd format

handlers/handlers.go
The logger is already `.WithError()` so the current impl just pastes the
error twice in a log.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/assign @alvaroaleman
=> handlers: stop double-logging errors

images/boskosctl/Dockerfile
There is no golang:1.16.6-alpine3.12 image, just
golang:1.16.6-alpine3.14
Ref https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-boskos-push-images/1421159064083107840 for the failing postsubmit
=> Fix image build

cmd/janitor/gcp_janitor.py
1. Update `ZONES` list for GCP janitor by running `gcloud compute zones list --format="value(name)" | sort | awk '{print "    \x27"$1"\x27," }'`
2. Fix "WARNING: Flag `--zones` is deprecated. Use `--filter="zone:( ZONE ... )"` instead."
/cc @ixdy
=> [GCP janitor] Update ZONES and use the new filter syntax

hack/verify/verify_boilerplate.py
As seen in #101, `verify_boilerplate.py` has started failing.
I believe this is because the `golang:1.16` image is now based on Debian Bullseye, which I guess has deprecated the `python` alias (finally).
I ran `2to3 -p -e -w hack/verify/verify_boilerplate.py` to update this script.
/assign @chizhg
=> Update verify_boilerplate to python3

cmd/boskos/boskos.go, crds/client.go, deployments/base/rbac.yaml
This change optionally makes the Boskos server use leader election. This
allows to have multiple replicas running of which only one is active in
order to reduce downtime when one replica gets unavailable.
=> Boskos: Allow HA by adding optional leader election

images/cloudbuild.yaml
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523
- Followup to: https://github.com/kubernetes/test-infra/pull/23656
=> images: use k8s-staging-test-infra/gcb-docker-gcloud

.golangci.yml, cmd/boskos/boskos.go, crds/client.go, deployments/base/deployment.yaml, deployments/base/rbac.yaml, deployments/base/service.yaml, leaderlabelreconciler/leaderlabelreconciler.go, leaderlabelreconciler/leaderlabelreconciler_test.go
This change adds a small controller to boskos that will make it manage a
label on pods. The label will be set on the pod that has the leader
lease and removed on all other pods. This in turn allows to have
multiple replicas of boskos running by using a service that targets said
label.
It makes the new `--boskos-label-selector` and `--pod-name` flags mandatory when `--enable-leader-election` is set.
Apart from the included unit tests I also manually deployed and tested this with kind:
```
$ k get pod -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP            NODE                 NOMINATED NODE   READINESS GATES
boskos-5dfb47b97b-gsgcx   1/1     Running   0          18m   10.244.0.26   kind-control-plane   <none>           <none>
boskos-5dfb47b97b-hbcd8   1/1 …
```
=> Boskos: Manage a label that denotes leader to allow HA setups

deployments/base/cleaner/deployment.yaml, deployments/base/crd.yaml, deployments/base/deployment.yaml, deployments/base/janitor/deployment.yaml, deployments/base/reaper/deployment.yaml
Related:
- https://github.com/kubernetes-sigs/boskos/issues/94
These are the changes necessary to bring the CRD definition in line with changes called out in https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122
WIP because:
- needs upgrade testing
The biggest change here is that the schema is now required. I wrote this
by looking at the types in crd/ and common/. Any field that was a map
got a `x-kubernetes-preserve-unknown-fields: true`
The most controversial change is probably adding the api-approved
annotation, to allow us to keep using the .k8s.io group. This should
mean that updating the CRD doesn't require migrating any of the
resources. As prior art, I'm looking at the fact that prow.k8s.io
did the same thing for its ProwJob CRD.
This is …
=> Update CRDs to apiextensions.k8s.io/v1

cmd/janitor/gcp_janitor.py
The boolean var name and the function name cannot be the same. Rename the boolean var to avoid conflicts.
/cc @krzyzacy
=> Fix a bug for GCP janitor introduced by #116

common/ibmcloud/common.go, internal/ibmcloud-janitor/account/account.go, internal/ibmcloud-janitor/resources/powervs_client.go, internal/ibmcloud-janitor/resources/serviceid.go, internal/ibmcloud-janitor/resources/serviceid_client.go
This PR makes the following changes:
- Does not load the API key as a part of the resource user data
- Uses the Janitor's API key for fetching the account ID
Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>
=> Ignore loading API key

aws-janitor/resources/set.go, aws-janitor/resources/set_test.go
This stops us deleting objects that are repeatedly recreated with the
same name, as long as the creation time is passed in.
Issue #132
=> aws-janitor: Use the creation time if it is specified

aws-janitor/resources/list.go, aws-janitor/resources/target_groups.go, cmd/aws-janitor-boskos/main.go, cmd/aws-janitor/main.go, cmd/aws-resources-list/main.go
For now, the target groups(https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#TargetGroup) are not GCed by the aws-janitor, this change intends to support that.
TESTED=I run make, make test and make verify locally, not error found.
Tried:
go run cmd/aws-janitor/main.go --dry-run=true --all=true
go run cmd/aws-janitor/main.go --dry-run=true --all=true --enable-target-group-clean=true
locally
The log looks good to me
=> Support target groups deletion in aws-janitor repo.

Makefile
This may be the cause for image building breaking after #137
=> Bump default golang version used by make targets

images/boskosctl/Dockerfile
Build still breaking. Old alpine version this time.
/cc @alvaroaleman @chaodaiG
=> Bump alpine version used for the boskosctl image

cmd/janitor/gcp_janitor.py
As discussed in https://github.com/kubernetes-sigs/boskos/issues/142,
the GCP janitor isn't thread-safe: sometimes, it can corrupt the GCloud
config file (which is on-disk, and which is shared by all threads).
Instead of using "gcloud config set X/Y Z", use
"os.environ['CLOUDSDK_X_Y'] = Z".
=> Make GCP janitor thread-safe

aws-janitor/resources/list.go, aws-janitor/resources/vpc_endpoints.go, cmd/aws-janitor-boskos/main.go, cmd/aws-janitor/main.go, cmd/aws-resources-list/main.go
For now, the vpc endpoints(https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeVpcEndpoints) are not GCed by the aws-janitor, this change intends to support that.
TESTED=I run make, make test and make verify locally, not error found.
Tried:
go run cmd/aws-janitor/main.go --dry-run=true --all=true
go run cmd/aws-janitor/main.go --dry-run=true --all=true --enable-vpc-endpoints-clean=true
locally
The log looks good to me
=> Support vpc endpoints deletion in aws-janitor repo

aws-janitor/resources/iam_oidc_providers.go, aws-janitor/resources/list.go
We've observed these occasionally leaking, and there's a per-account
limit of 100.
=> AWS Janitor: Clean up IAM OIDC Provider resources also

aws-janitor/resources/list.go, aws-janitor/resources/route53.go, cmd/aws-janitor-boskos/main.go, cmd/aws-janitor/main.go, cmd/aws-resources-list/main.go
Add a flag to skip management check for route32 zones and resources
tried
go run cmd/aws-janitor/main.go --dry-run=true --all=true --skip-route53-management-check=true
locally
The log looks good to me
=> Skip management check for route35 zones and resources

aws-janitor/resources/iam_roles.go, aws-janitor/resources/list.go
Many iam roles fail to be deleted due to attached policies they have. Before deleting iam roles, we should also detach those role policies.
=> Fix a bug for aws iam roles clean up

aws-janitor/resources/list.go, aws-janitor/resources/route53.go, cmd/aws-janitor-boskos/main.go, cmd/aws-janitor/main.go
Currently, we have error log:
unable to delete DNS records: InvalidChangeBatch: [A HostedZone must contain at least one NS record for the zone itself., A HostedZone must contain exactly one SOA record.]
Which means that the type "NS" and "SOA" should not be deleted.
=> Skip some resource record set types when deleting resource records

aws-janitor/resources/internet_gateways.go
Reverts kubernetes-sigs/boskos#158
The public IP association can be nil, thus when running DescribeNetworkInterfacesPages, it sometimes fail, causing cleanup to panic in certain cases.
Also, deleting network interfaces should disassociate automatically, so likely we don't need this change.
=> Revert "Disassociate elastic IP address when detaching Internet Gateway"

internal/ibmcloud-janitor/resources/types.go, internal/ibmcloud-janitor/resources/util.go, internal/ibmcloud-janitor/resources/vpc_client.go, internal/ibmcloud-janitor/resources/vpc_lbs.go
Add cleanup of load balancers for VPC resources
=> Add cleanup for VPC load balancers

ranch/ranch_test.go, ranch/storage.go
`boskos` doesn't currently support moving a static resource name from one type to another; this PR tries fill the gap and overcome this limitation.
Example (as-is):
The following configuration:
```yaml
resources:
- type: type-0
names:
- type-0-name-0
- type-0-name-1
state: free
- type: type-1
names:
- type-1-name-0
state: free
```
produces these resources:
```sh
$ oc get resources
NAME            TYPE     STATE   OWNER   LAST-UPDATED
type-0-name-0   type-0   free            60m
type-0-name-1   type-0   free            60m
type-1-name-0   type-1   free            60m
```
but when it changes to:
```yaml
resources:
- type: type-0
names:
- type-0-name-0
state: free
- type: type-1
names:
- type-1-name-0
- type-0-name-1
state: free
```
the resources aren't updated accordingly:
```sh
$ oc get …
```
=> `boskos`: move names over different types

cmd/janitor/gcp_janitor.py
Without that flag Janitor might be unalbe to cleanup resource, as some nested dependencies (like snapshots) might block deletion.
=> [gcp_janitor] Add '--force' flag for filestore API

images/janitor/Dockerfile
gcloud behaviour has been changed recently for registering a cluster in a fleet. Now default behaviour is to register in cluster's region and not global. Previous gcloud versions still try to un-register from global location only and are not forward compatible.
=> Update gcloud version to the latest for the janitor image

Makefile, cmd/janitor/gcp_janitor.py
Janitor is failing to delete networks because they have ip ranges left over from tests. Adding a way to figure the secondary ip ranges and delete them before starting cluster deletion.
=> Adds extra step to delete secondary ip ranges before cluster deletion

cmd/janitor/gcp_janitor.py
* Add ssl-policies to the list of resources for cleanup.
* Cleanup should be done for both regional and glocal policies.
=> gcp_janitor.py: cleanup ssl-policies

cmd/janitor/gcp_janitor.py
* Add security-policies to the list of resources for cleanup.
* Cleanup should be done for both regional and glocal policies.
* Security policies have dependencies on backend services, target pools, target instances, and instances. Thus, its cleanup should be after the cleanups of these resources.
=> gcp_janitor.py: cleanup security-policies

cmd/janitor/gcp_janitor.py
Based on https://cloud.google.com/load-balancing/docs/use-ssl-policies#delete-policy, ssl-policies should be cleaned up after target-https-proxies.
/assign @krzyzacy
=> ssl-policies should be cleaned up after target-https-proxies.

OWNERS
I'm the initial author and recently jumping back to OSS universe, add myself back to owners so that I can stamp related CI/config changes
=> Add krzyzacy@ back to OWNERS

images/boskosctl/Dockerfile
golang:1.19.12-alpine3.16 doesn't actually exist and is causing the image postsubmit to fail:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-boskos-push-images/1755036868031811584
=> Bump alpine_version in boskosctl image to 3.17.

aws-janitor/resources/iam_oidc_providers.go
aws-janitor is not cleaning up OIDC providers created by `eksctl` during EKS cluster creation process in the community account. This PR resolves https://github.com/kubernetes/k8s.io/issues/6300
cc: @dims
=> Cleanup OIDC providers created by eksctl for `ci-shared-aws`

cmd/janitor/janitor.go, cmd/reaper/reaper.go, common/resource_types.go, common/resource_types_test.go
Building on top of https://github.com/kubernetes-sigs/boskos/pull/157
This PR allows the janitor to read the resource types from the given config file instead of reading directly from the arguments. Upon updates to the resource types, the janitor can reload the types on the file so no need to restart the deployment.
=> Allow janitor to reload resource types from a config file

cmd/janitor/gcp_janitor.py
If network resource is left in the project, it's possible that we will leak internal-ranges object.
This change adds internal-ranges as an additional resource to deletion
=> [gcp_janitor.py] Add removal of internal-ranges

Makefile, images/boskosctl/Dockerfile
Docker image fails to build, logs are [here](https://storage.googleapis.com/kubernetes-jenkins/logs/post-boskos-push-images/1818709268862341120/build-log.txt).
```
Step 1/18 : ARG go_version
Step 2/18 : ARG alpine_version=3.17
Step 3/18 : FROM golang:${go_version}-alpine${alpine_version} as build
manifest for golang:1.22.3-alpine3.17 not found: manifest unknown: manifest unknown
make: *** [Makefile:78: boskosctl-image] Error 1
ERROR
ERROR: build step 0 "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20210917-12df099d55" failed: step exited with non-zero status: 2
```
Pick a newer image [docker.io/library/golang](https://explore.ggcr.dev/?repo=docker.io/library/golang):[1.22.5-alpine3.20](https://explore.ggcr.dev/?image=docker.io/library/golang:1.22.5-alpine3.20&mt=application%2Fvnd.oci.i …
=> Bump Go and Alpine versions

images/default/Dockerfile
We reverted the previous image because of GLIBC issue https://github.com/kubernetes/test-infra/pull/33184
let's switch to newer debian which is used in k/release and elsewhere:
https://cs.k8s.io/?q=gcr.io%2Fdistroless%2Fbase-debian1&i=nope&files=&excludeFiles=&repos=
=> Update to debian12 to get latest glibc

aws-janitor/s3/s3.go
Failure in:
- https://storage.googleapis.com/kubernetes-jenkins/logs/maintenance-ci-shared-aws-janitor/1818809423779336192/build-log.txt
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-aws-ec2-janitor/1818809392036843520/build-log.txt
Because i missed some logic when converting from v1 to v2, specifically:
https://github.com/kubernetes-sigs/boskos/blame/210745d604c7bcd375251640e39b076a3467cb43/aws-janitor/s3/s3.go#L53-L56
=> Use default region if LocationConstraint not found from s3 bucket

cmd/boskosctl/README.md
Use standard boskos released projects state = dirty in boskosctl example
The standard expected states are here:
https://github.com/kubernetes-sigs/boskos/blob/1221bfe2f633fe5eea83125d32b782c07204c2e9/common/common.go#L30-L46
I think this explains why we have some projects stuck in state "other", it got copy-pasted to image-builder here: https://github.com/kubernetes-sigs/image-builder/blob/f09c4f6be1aa2916ff27d23b459e8fb536a058ca/images/capi/scripts/ci-gce.sh#L53
We should use "dirty" for the example, because that works with the janitors and is a well-known target state.
=> Use standard boskos released projects state = dirty in boskosctl example

cmd/janitor/gcp_janitor.py
Reverts kubernetes-sigs/boskos#193.
After bumping Boskos janitor version, our projects were stuck in the `cleaning` state. Janitor's logs inspection proves that this PR is at fault here - sample log entry:
```
ERROR: (gcloud) Invalid choice: 'secretmanager'.
Maybe you meant:
gcloud secrets list
gcloud secrets locations list
gcloud secrets versions list
gcloud ai custom-jobs list
gcloud ai endpoints list
gcloud ai hp-tuning-jobs list
gcloud ai index-endpoints list
gcloud ai indexes list
gcloud ai model-monitoring-jobs list
gcloud ai models list
To search the help text of gcloud commands, run:
gcloud help -- SEARCH_TERMS
Fail to list resource 'secrets' from project 'gke-scalability-4': CalledProcessError(2, ['gcloud', 'secretmanager', '-q', 'secrets', 'list', …
```
=> Revert "Updated gcp_janitor.py to clean secret manager resources"

cmd/ibmcloud-janitor-boskos/main.go, internal/ibmcloud-janitor/resources/clean.go, internal/ibmcloud-janitor/resources/types.go
Add a flag to skip cleanup and rotation of API Keys. This will avoid adding key details to the user data of a resource.
```
./boskosctl acquire --type powervs-service --state free --target-state busy --owner-name amulya --server-url http://localhost:8080 
{"type":"powervs-service","name":"amulya-test-2","state":"busy","owner":"amulya","lastupdate":"2024-10-25T15:27:06.964236+05:30","userdata":{"resource-group":"XXX","service-instance-id":"XXX","zone":"lon04"}}
./boskosctl release --name amulya-test-2 --target-state dirty --owner-name amulya --server-url http://localhost:8080                                    
released resource "amulya-test-2"
go run cmd/ibmcloud-janitor-boskos/main.go --boskos-url=http://localhost:8080 -ignore-api-key=true -resource-type powervs-service …
```
=> Add a flag to ignore API key management

cmd/janitor/gcp_janitor.py
I am working on-recreating a prow job and these prow jobs deleted during migration to community infra. [Discussion ref](https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU).
I am re-enabling this [job](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/secrets-store-csi-driver/secrets-store-csi-driver-config.yaml#L682-L725) to run on community infra. 
To run the job in community infra, I need to create secrets from google secret manager.
This PR is to remove secrets created during the job execution.
=> Clean up secrets created during the tests.

images/cloudbuild.yaml
#219 failed because the buildx version is too old, bumping to latest
=> use a newer version of buildx

cmd/ibmcloud-janitor-boskos/main.go, internal/ibmcloud-janitor/resources/powervs_client.go, internal/ibmcloud-janitor/resources/serviceid.go, internal/ibmcloud-janitor/resources/types.go
This PR adds a flag to pass account ID as a flag and use it or fetch the account ID using the API key.
=> Add a flag to pass account ID in ibmcloud-janitor

common/ibmcloud/common.go, internal/ibmcloud-janitor/resources/vpc.go, internal/ibmcloud-janitor/resources/vpc_client.go, internal/ibmcloud-janitor/resources/vpc_instances.go, internal/ibmcloud-janitor/resources/vpc_lbs.go, internal/ibmcloud-janitor/resources/vpc_networks.go
Enhances the IBM Cloud Janitor functionality to support resource cleanup based on a specific VPC ID.
Changes Introduced:
- Added conditional logic to clean up resources (subnets, floating IPs, load balancers) based on the VPC they are associated with.
- When `vpc-id` is passed in the API call, the janitor filters and deletes:
- Subnets within the specified VPC
- Unbound floating IPs (with conditional checks if VPC is specified)
- Load balancers attached to subnets belonging to the specified VPC
- If `vpc-id` is not provided, the cleanup falls back to using the resource group as the default filter.
Why:
This allows more granular and targeted cleanup, especially useful when multiple VPCs exist under the same resource group.
=> Janitor Cleanup Based on VPC ID

Makefile, images/build.sh
This PR adds changes for enabling multi arch build for boskos images for s390x platform.
Issue: https://github.com/kubernetes-sigs/boskos/issues/221
=> Build and push multi-arch images for platform s390x

images/cloudbuild.yaml
The boskos images build has been timing out, this PR increases the timeout to 3600s.
=> Increase timeout for image build

cmd/ibmcloud-janitor-boskos/main.go, internal/ibmcloud-janitor/resources/clean.go
This PR adds a feature to set a resource state to noSchedule when a tag is added to a PowerVS workspace. This will avoid it from being used for jobs or by janitor for cleanup until the tag is present.
Also, added more log statements and refactored the main to remove check for linter nestif.
=> Enhance the flow to skip PowerVS resource clean up using new state
