kubernetes-sigs/boskos

hack/verify/verify_boilerplate.py
take 2 (still testing locally)
=> Fix verify_boilerplate to work in python2

cmd/boskos/boskos.go, cmd/cleaner/main.go, cmd/fake-mason/main.go, cmd/metrics/metrics.go, crds/client.go, go.mod, go.sum
Mostly this is for https://github.com/kubernetes/test-infra/pull/17976.
=> Update k8s.io/test-infra dependency and refactor some flags handling

aws-janitor/resources/set.go, cmd/aws-resources-list/main.go
Similar functionality already exists in the AWS janitor.
=> aws-resources-list: support listing all regions

cmd/janitor/gcp_janitor.py
This approach is a little dumb: it uses the creation timestamp for a GKE Hub membership registration, like every other resource.
A better way would be to identify which memberships are stale (i.e. if there's no connected cluster), but I don't see an easy way to do that using the gcloud command line. (It just lists all memberships as `READY`?)
I also regret adding more functionality to this python script, but it's fairly lightweight...
=> GCP janitor: add support for GKE Hub memberships

cmd/checkconfig/main.go, common/config.go, common/config_test.go, go.mod
=> Improve config validation and add checkconfig cmd

images/cloudbuild.yaml
I thought just having `make` build it would be enough :grimacing:
=> Build checkconfig image

cmd/aws-janitor-boskos/main.go, common/aws/common.go
Changes related to utilizing boskos for image-builder CI, 
https://github.com/kubernetes/test-infra/pull/19645
Please let me know if I have missed anything. 
CC: @detiber
=> support boskos resource of type image-builder-aws-account

cmd/reaper/reaper.go
Currently we create a log entry every time we issued an api call,
regardless of if it actually did something or not. This commit:
* Makes sure we only log when something was actually cleaned
* Makes us use log fields in the reaper
=> Reaper: Cleanup logging

cmd/boskos/boskos.go, crds/client.go
This PR restores boskos in-memory mode which I broke in https://github.com/kubernetes-sigs/boskos/pull/54. It does so by moving the client construction back into the crd/ package but returning a `Manager` as we need that for our config sync controller.
If in-memory mode is enabled, the `Manager` will have custom constructors for everything that would talk to a cluster that instead return a fake implementation.
This results in the config sync controller never getting triggered, so the config sync is once called explicitly in `main`.
I verified this change by running boskos with in-memory mode and without access to a cluster locally and checking that I was able to acquire a resource with curl:
```bash
$ curl -XPOST 'localhost:8080/acquire?type=vsphere-quota-slice&state=free&dest=nonfree&owne …
```
=> Restore in-memory mode

common/config.go, common/config_test.go
=> Validate that resources are either static or dynamic

aws-janitor/resources/eks.go, aws-janitor/resources/list.go
/hold
(since this is dependent on #59)
/assign @detiber 
cc @chemikadze
=> aws-janitor: add support for EKS clusters

crds/client.go
[Projected service acccount token volumes][0] allow to set up a
tokenfile that will be automatically rotated by the kubelet. Setting the
BearerTokenFile option on the restcfg for this will make client-go
periodically reload it.
[0]: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection
=> Add support for token rotation by allowing to set a projected token file

cmd/boskosctl/README.md
Add instructions in how to install `boskosctl` using go get
/cc @detiber
=> boskosctl/readme: add how to install boskosctl instructions

aws-janitor/resources/asg.go, aws-janitor/resources/cloud_formation_stacks.go, aws-janitor/resources/efs.go, aws-janitor/resources/elb.go, aws-janitor/resources/launch_configs.go, aws-janitor/resources/route53.go, aws-janitor/resources/snapshots.go, go.mod, go.sum
Normalize the ARN for resources that do not have.
/assign @ixdy 
please let me know if that makes sense or what you think, thanks for your review in advance :)
Fixes: https://github.com/kubernetes-sigs/boskos/issues/55
=> aws-janitor: normalize generated arn ids for resources

aws-janitor/resources/cloud_formation_stacks.go, aws-janitor/resources/snapshots.go
Minor follow-up to #67.
/assign @cpanato
=> aws-janitor: fix ARN for snapshots and CFS

aws-janitor/resources/iam_instance_profiles.go, aws-janitor/resources/iam_roles.go
One additional safeguard is added: any role which has been used within the specified TTL will not be deleted.
/assign @richardcase @randomvariable
cc @chemikadze
This one is a bit shorter, hopefully isn't too much of a pain to review. :)
=> aws-janitor: manage all IAM roles except system roles

cmd/janitor/gcp_janitor.py
Fixes https://github.com/kubernetes-sigs/boskos/issues/100
/cc @ixdy
=> Allow specifying additional zones for GCP janitor

cmd/janitor/gcp_janitor.py
Add autopush-gkehub endpoint for cleaning up memberships.
=> add clean up membership in autopush hub

images/janitor/Dockerfile, images/janitor/OWNERS
It's been two years old, so it's the time to bump it, instead of investigate any issues that are potentially related to a stale version.
/cc @krzyzacy 
FYI @chaodaiG @coryrc
=> Update gcloud SDK version to the latest for the janitor image

cmd/janitor/gcp_janitor.py
Currently all the gcloud API requests are by default using the quota of the service account's project, which does not scale when there are a lot of projects in the Boskos project pools.
This PR adds an option to gcp janitor to allow setting quota project as the project to be cleaned up, which distributes the API request load evenly to each project. Since this'll request all the projects to have the corresponding APIs enabled, defaulting the flag value to be False to allow opt-in.
/cc @krzyzacy
=> Add an option for gcp janitor to allow setting quota project

client/client.go, client/client_test.go, common/common.go, ranch/ranch.go
=> Distinguish between resources busy and unknown resource type

aws-janitor/resources/internet_gateways.go
According to AWS tutorial:
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html#detach-igw The elastic ip should be disassociated before detaching vpc internet gateway.
=> Disassociate elastic IP address when detaching Internet Gateway

aws-janitor/account/account.go
Use sts `GetCallerIdentity` when `GetUser` fails... tested with the following on a federation system that uses assume role
```
aws-janitor \
--ttl=0 \
--region=us-west-2 \
--dry-run=false \
--log-level=debug \
--exclude-tags=isengard \
--enable-target-group-clean \
--enable-vpc-endpoints-clean \
--enable-dns-zone-clean \
--path="s3://aws-janitor/cleanup"
```
without this patch, we were getting:
```
An error occurred (ValidationError) when calling the GetUser operation:
Must specify userName when calling with non-User credentials
```
=> Work in federated / assume role scenarios"

cmd/janitor/gcp_janitor.py
Example PR for Filestore: https://github.com/kubernetes-sigs/boskos/pull/111
=> Add Parallelstore instance support to GCP Janitor

OWNERS, OWNERS_ALIASES
Match what is in https://github.com/kubernetes/test-infra/blob/39af7766d3d73431e2ef4d309faed0309b07b428/OWNERS_ALIASES#L3-L18
=> sync aliases from k/test-infra

cmd/janitor/gcp_janitor.py
Fix: https://github.com/kubernetes-sigs/boskos/issues/209
=> Check Secret Manager API before cleaning secrets

OWNERS, SECURITY_CONTACTS
Unfortunately I do not have the capacity to be active as a maintainer of boskos, hence removing myself.
=> Remove alvaroaleman from owners
